apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-demo-deployment
  labels:
    app: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: banking-container
          image: image-registry.openshift-image-registry.svc:5000/mallela-haribabu-dev/openshift-demo-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
